// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcQmIr69tYWrVmAHxnib5dpyFr7vgClK4',
    appId: '1:841576473606:web:5614d3d923b3a061724f87',
    messagingSenderId: '841576473606',
    projectId: 'mess-app-aabf2',
    authDomain: 'mess-app-aabf2.firebaseapp.com',
    storageBucket: 'mess-app-aabf2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWlgAMAfppl_X9o0eNFY5sLjyvBvQXssU',
    appId: '1:841576473606:android:5d3cc0b842205bd2724f87',
    messagingSenderId: '841576473606',
    projectId: 'mess-app-aabf2',
    storageBucket: 'mess-app-aabf2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1NMtbJFpAZUo15PlaAQL78rmUSKMhORA',
    appId: '1:841576473606:ios:45c9a91dfb9c69c4724f87',
    messagingSenderId: '841576473606',
    projectId: 'mess-app-aabf2',
    storageBucket: 'mess-app-aabf2.appspot.com',
    iosBundleId: 'com.example.messApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1NMtbJFpAZUo15PlaAQL78rmUSKMhORA',
    appId: '1:841576473606:ios:f393645f629a90c9724f87',
    messagingSenderId: '841576473606',
    projectId: 'mess-app-aabf2',
    storageBucket: 'mess-app-aabf2.appspot.com',
    iosBundleId: 'com.example.messApp.RunnerTests',
  );
}
