// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCC_sap7uhKWhKXDpTmq0yCfcRzC3v4c3w',
    appId: '1:918909975447:web:611f3a73da9184b9b2e2d2',
    messagingSenderId: '918909975447',
    projectId: 'mess-app-2',
    authDomain: 'mess-app-2.firebaseapp.com',
    storageBucket: 'mess-app-2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWdhCSmcz8PWXEftYX7wc4hvCI4dHHADs',
    appId: '1:918909975447:android:9767b62c86ae79d5b2e2d2',
    messagingSenderId: '918909975447',
    projectId: 'mess-app-2',
    storageBucket: 'mess-app-2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAO870KxN7Jwor9NlTGWbcEeHvWWJVgv6U',
    appId: '1:918909975447:ios:cc481db58d081f40b2e2d2',
    messagingSenderId: '918909975447',
    projectId: 'mess-app-2',
    storageBucket: 'mess-app-2.appspot.com',
    iosBundleId: 'com.example.messApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAO870KxN7Jwor9NlTGWbcEeHvWWJVgv6U',
    appId: '1:918909975447:ios:3dc17c8741db141cb2e2d2',
    messagingSenderId: '918909975447',
    projectId: 'mess-app-2',
    storageBucket: 'mess-app-2.appspot.com',
    iosBundleId: 'com.example.messApp.RunnerTests',
  );
}
